# Generated by Django 3.2.8 on 2021-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantages',
            options={'verbose_name': 'Xizmatlar texnologiyalari', 'verbose_name_plural': 'Xizmatlar texnologiyalari'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Xabarlar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Asosiy', 'verbose_name_plural': 'Asosiy'},
        ),
        migrations.AlterModelOptions(
            name='modal_texnology',
            options={'verbose_name': 'Xizmat turi texnologiyalari', 'verbose_name_plural': 'Xizmat turi texnologiyalari'},
        ),
        migrations.AlterModelOptions(
            name='plan_type',
            options={'verbose_name': 'Tariflar', 'verbose_name_plural': 'Tariflar'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'Narxlar', 'verbose_name_plural': 'Narxlar'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projectlar', 'verbose_name_plural': 'Projectlar'},
        ),
        migrations.AlterModelOptions(
            name='projects_type',
            options={'verbose_name': 'Project turlari', 'verbose_name_plural': 'Project turlari'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmatlar', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='service_about',
            options={'verbose_name': 'Xizmat haqida', 'verbose_name_plural': 'Xizmat haqida'},
        ),
        migrations.AlterModelOptions(
            name='service_about2',
            options={'verbose_name': 'Xizmat haqida 2', 'verbose_name_plural': 'Xizmat haqida 2'},
        ),
        migrations.AlterModelOptions(
            name='service_modal',
            options={'verbose_name': 'Xizmat turi modeli', 'verbose_name_plural': 'Xizmat turi modeli'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Izoxlar', 'verbose_name_plural': 'Izoxlar'},
        ),
        migrations.AlterModelOptions(
            name='work_tpye',
            options={'verbose_name': 'Xizmat turi', 'verbose_name_plural': 'Xizmat turi'},
        ),
        migrations.AlterField(
            model_name='service',
            name='service_info',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service_about2',
            name='info_title',
            field=models.TextField(max_length=220),
        ),
        migrations.AlterField(
            model_name='service_about2',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
